---
apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-service-config
  namespace: final-proj
data:
  SERVER_ADDR: ":8080"
  BROKER_TYPE: "KAFKA"
  DB_HOST: "postgres-profiles"
  DB_PORT: "5432"
  DB_NAME: "profiledb"
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_PROFILE_TOPIC: "profile"
  KAFKA_BILLING_TOPIC: "billing"
  KAFKA_BILLING_GROUP: "profilesvc.billing"
  KAFKA_PROFILE_CREATED_EVENT_TYPE: "profile.created"
  KAFKA_BILLING_ACCOUNT_CREATED_EVENT_TYPE: "billing.account.created"
  BILLING_URL: "http://billing-service:8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: profile-service-secret
  namespace: final-proj
type: Opaque
stringData:
  DB_USER: "profile_user"
  DB_PASSWORD: "profile_password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  namespace: final-proj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ["sh","-c","until nc -z postgres-profiles 5432; do echo waiting...; sleep 2; done"]
          resources:
            requests: { cpu: "10m", memory: "16Mi" }
            limits:   { cpu: "50m", memory: "32Mi" }
      containers:
        - name: profile-service
          image: mblkuta/profile-service:finalproj-latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: profile-service-config
            - secretRef:
                name: profile-service-secret
            - secretRef:
                name: shared-secrets
          readinessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits:   { cpu: "200m", memory: "128Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: final-proj
spec:
  selector:
    app: profile-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
