INSERT INTO public.category VALUES ('000000', 'Root', '000000');
INSERT INTO public.category VALUES ('9xg2k1', 'Одежда', '000000');
INSERT INTO public.category VALUES ('8t7m3z', 'Для мужчин', '9xg2k1');
INSERT INTO public.category VALUES ('4jf92l', 'Для женщин', '9xg2k1');
INSERT INTO public.category VALUES ('m5c1q7', 'Аксессуары', '9xg2k1');
INSERT INTO public.category VALUES ('z6n4y2', 'Рубашки', '8t7m3z');
INSERT INTO public.category VALUES ('q7l5m2', 'Куртки', '8t7m3z');
INSERT INTO public.category VALUES ('p3k8y4', 'Обувь', '8t7m3z');
INSERT INTO public.category VALUES ('b2m4q9', 'Платья', '4jf92l');
INSERT INTO public.category VALUES ('c8k5v7', 'Юбки', '4jf92l');
INSERT INTO public.category VALUES ('y4n3x1', 'Блузки', '4jf92l');
INSERT INTO public.category VALUES ('d6t9l2', 'Обувь', '4jf92l');
INSERT INTO public.category VALUES ('v5k3y8', 'Часы', 'm5c1q7');
INSERT INTO public.category VALUES ('w8n2l4', 'Сумки', 'm5c1q7');
INSERT INTO public.category VALUES ('t7q9x1', 'Шляпы', 'm5c1q7');
INSERT INTO public.category VALUES ('a7o5z3', 'Футболки', '8t7m3z');
INSERT INTO public.category VALUES ('x9v3t5', 'Штаны', '8t7m3z');
INSERT INTO public.category VALUES ('wsh20m', 'Туфли', 'd6t9l2');
INSERT INTO public.category VALUES ('wsh3hk', 'Ботинки', 'd6t9l2');
INSERT INTO public.category VALUES ('wsh4o5', 'Сандалии', 'd6t9l2');
INSERT INTO public.category VALUES ('mpa17w', 'Джинсы', 'x9v3t5');
INSERT INTO public.category VALUES ('mpa37b', 'Шорты', 'x9v3t5');
INSERT INTO public.category VALUES ('mpa4kk', 'Спортивные штаны', 'x9v3t5');
INSERT INTO public.category VALUES ('mja1xv', 'Пальто', 'q7l5m2');
INSERT INTO public.category VALUES ('mja24d', 'Пуховики', 'q7l5m2');
INSERT INTO public.category VALUES ('mja3ur', 'Ветровки', 'q7l5m2');
INSERT INTO public.category VALUES ('acc135', 'Очки', 'm5c1q7');
INSERT INTO public.category VALUES ('acc293', 'Ремни', 'm5c1q7');
INSERT INTO public.category VALUES ('acc38r', 'Кошельки', 'm5c1q7');
INSERT INTO public.category VALUES ('mpa2ry', 'Брюки', 'x9v3t5');
INSERT INTO public.category VALUES ('msh1yd', 'Кроссовки', 'p3k8y4');
INSERT INTO public.category VALUES ('msh2u7', 'Туфли', 'p3k8y4');
INSERT INTO public.category VALUES ('msh3bo', 'Ботинки', 'p3k8y4');
INSERT INTO public.category VALUES ('msh4nq', 'Сандалии', 'p3k8y4');
INSERT INTO public.category VALUES ('wsh1on', 'Кроссовки', 'd6t9l2');